version: '2'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    volumes:
    - logvolume01:/var/log
    depends_on:
    - smtp
  smtp:
    image: namshi/smtp
    ports:
    - "25:25"
volumes:
  logvolume01: {}